"use client";
import { useEffect, useState } from "react"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { useToast } from "@/components/ui/toast";
import { rolesApi, type Permission, type Role } from "@/lib/api/roles"; import { usersApi, type AppUser } from "@/lib/api/users";
const normalizeRoleCode = (value:string) => value.trimStart().toUpperCase().replace(/[.\s-]+/g,"_").replace(/[^A-Z0-9_]/g,"").replace(/_+/g,"_");
export default function RolesPage() {
  const { showToast } = useToast(); const [roles,setRoles]=useState<Role[]>([]); const [permissions,setPermissions]=useState<Permission[]>([]); const [users,setUsers]=useState<AppUser[]>([]); const [code,setCode]=useState(""); const [name,setName]=useState(""); const [error,setError]=useState("");
  async function load(){ try { const [r,p,u]=await Promise.all([rolesApi.list(),rolesApi.permissions(),usersApi.search({page:1,limit:100})]); setRoles(r);setPermissions(p);setUsers(u.items); } catch(e){setError(e instanceof Error?e.message:"Không thể tải dữ liệu.");} } useEffect(()=>{void Promise.all([rolesApi.list(),rolesApi.permissions(),usersApi.search({page:1,limit:100})]).then(([r,p,u])=>{setRoles(r);setPermissions(p);setUsers(u.items)}).catch(e=>setError(e instanceof Error?e.message:"Không thể tải dữ liệu."));},[]);
  async function create(e:React.FormEvent){e.preventDefault();const normalizedCode=normalizeRoleCode(code).replace(/^_+|_+$/g,"");setCode(normalizedCode);try{await rolesApi.create({code:normalizedCode,name:name.trim(),scope:"GLOBAL"});setCode("");setName("");await load();showToast("Đã tạo vai trò.","success");}catch(e){showToast(e instanceof Error?e.message:"Tạo thất bại.","error");}}
  async function toggle(role:Role, permission:Permission){try{if(role.permissions.some(x=>x.id===permission.id))await rolesApi.removePermission(role.id,permission.id);else await rolesApi.addPermission(role.id,permission.id);await load();}catch(e){showToast(e instanceof Error?e.message:"Cập nhật quyền thất bại.","error");}}
  async function assign(user:AppUser,roleId:string){try{await usersApi.assignRole(user.id,roleId);await load();showToast("Đã gán vai trò.","success");}catch(e){showToast(e instanceof Error?e.message:"Gán vai trò thất bại.","error");}}
  return <div className="space-y-6"><h1 className="text-xl font-bold">Vai trò và phân quyền</h1>{error&&<p className="bg-red-50 p-3 text-red-700">{error}</p>}<form onSubmit={create} className="flex flex-wrap gap-2 rounded-xl bg-white p-4 shadow-sm"><div className="min-w-52 flex-1"><Input required minLength={2} value={code} onChange={e=>setCode(normalizeRoleCode(e.target.value))} placeholder="ROLE_CODE"/><p className="mt-1 text-xs text-slate-400">Dấu chấm, khoảng trắng và gạch ngang sẽ được đổi thành _.</p></div><div className="min-w-52 flex-1"><Input required value={name} onChange={e=>setName(e.target.value)} placeholder="Tên vai trò"/></div><Button>Tạo vai trò</Button></form><div className="grid gap-4 lg:grid-cols-2">{roles.map(role=><section key={role.id} className="rounded-xl bg-white p-4 shadow-sm"><h2 className="font-bold">{role.name} <span className="text-xs text-slate-400">{role.code}</span></h2><div className="mt-3 grid gap-2">{permissions.map(p=><label key={p.id} className="flex gap-2 text-xs"><input type="checkbox" checked={role.permissions.some(x=>x.id===p.id)} onChange={()=>toggle(role,p)}/>{p.code}</label>)}</div></section>)}</div><section className="rounded-xl bg-white shadow-sm"><h2 className="border-b border-slate-100 p-4 font-bold">Gán vai trò cho người dùng</h2>{users.map(user=><div key={user.id} className="flex items-center justify-between border-b border-slate-100 p-4"><div><p className="font-semibold">{user.fullName}</p><p className="text-xs text-slate-500">{user.email} · {user.assignedRoles.map(x=>x.roleCode).join(", ")||"Chưa có vai trò"}</p></div><select className="rounded-lg border border-slate-200 p-2 text-xs" defaultValue="" onChange={e=>{if(e.target.value)assign(user,e.target.value)}}><option value="">Gán vai trò…</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div>)}</section></div>;
}
