"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { useToast } from "@/components/ui/toast";
import { campaignsApi, type EmailCampaign } from "@/lib/api/campaigns";
export default function EmailCampaignsPage() {
  const { showToast } = useToast(); const [items, setItems] = useState<EmailCampaign[]>([]); const [subject, setSubject] = useState(""); const [body, setBody] = useState(""); const [campaignType, setType] = useState("NEW_BOOKS"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = () => campaignsApi.list().then(setItems).catch(e => setError(e.message)); useEffect(() => { load(); }, []);
  async function create(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const item = await campaignsApi.create({ subject, body, campaignType }); setItems(v => [item, ...v]); setSubject(""); setBody(""); showToast("Đã lưu bản nháp chiến dịch.", "success"); } catch (e) { const m = e instanceof Error ? e.message : "Không thể tạo chiến dịch."; setError(m); showToast(m, "error"); } finally { setBusy(false); } }
  async function send(id: string) { setBusy(true); try { const sent = await campaignsApi.send(id); setItems(v => v.map(x => x.id === id ? sent : x)); showToast(`Đã gửi ${sent.sentCount}/${sent.recipientCount} email.`, sent.failedCount ? "error" : "success"); } catch (e) { showToast(e instanceof Error ? e.message : "Gửi thất bại.", "error"); } finally { setBusy(false); } }
  return <div className="space-y-6"><h1 className="text-xl font-bold">Chiến dịch email</h1>{error && <p className="bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={create} className="grid gap-3 rounded-xl border bg-white p-5"><Input required value={subject} onChange={e => setSubject(e.target.value)} placeholder="Tiêu đề"/><select className="rounded-lg border p-2 text-sm" value={campaignType} onChange={e => setType(e.target.value)}><option>NEW_BOOKS</option><option>VOUCHER</option><option>FLASH_SALE</option></select><textarea required className="min-h-32 rounded-lg border p-3 text-sm" value={body} onChange={e => setBody(e.target.value)} placeholder="Nội dung HTML"/><Button disabled={busy}>Lưu bản nháp</Button></form><div className="rounded-xl border bg-white divide-y">{items.map(x => <div key={x.id} className="flex items-center justify-between p-4"><div><p className="font-semibold">{x.subject}</p><p className="text-xs text-slate-500">{x.campaignType} · {x.status} · gửi {x.sentCount}/{x.recipientCount} · lỗi {x.failedCount}</p></div><Button disabled={busy || x.status === "SENT"} onClick={() => send(x.id)}>Gửi</Button></div>)}{!items.length && <p className="p-6 text-center text-sm text-slate-400">Chưa có chiến dịch.</p>}</div></div>;
}
